<?php

namespace Tests\Feature;

use App\Models\Post;
use Faker\Factory as Faker;
use Tests\TestCase;

class CommentRequestTest extends TestCase
{
    public $faker;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->faker = Faker::create();
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function testLeaveABadComment()
    {
        $response = $this->json('POST', '/api/v1/comment', [
            'post_id' => '',
            'author' => '',
            'content' => ''
        ]);

        $response->assertResponseStatus(422);
    }

    /**
     * @group comment
     */
    public function testLeaveAComment()
    {
        $data = [
            'post_id' => Post::first()->id,
            'author' => 'Valid Name',
            'content' => 'qwe'
        ];

        $response = $this->postJson('/api/v1/comment', $data);

        $response->assertResponseStatus(201);
    }
}
