<?php

namespace Tests\Feature;

use Faker\Factory as Faker;
use Tests\TestCase;

class PostRequestTest extends TestCase
{
    public $faker;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->faker = Faker::create();
    }

    /**
     * A basic feature test example.
     *
     * @return void
     */
    public function testCreatePost()
    {
        $name = $this->faker->name;

        $this->visit('/post/create')
            ->type($name, 'name')
            ->type($this->faker->name, 'content')
            ->press('Save');
    }

    public function testUpdatePost()
    {
        $name = $this->faker->name;

        $this->visit('/post/1/edit');

        $this->submitForm('Save', [
            'name' => $name,
            'content' => $this->faker->text,
            'category_ids' => [1, 2],
        ])->see('Edit post: ' . $name);
    }
}
