<?php

namespace Tests\Unit;

use App\Models\UserAgentStatistic;
use App\Services\UserAgentService;
use Tests\TestCase;
use Faker\Factory as Faker;

class UserAgentTest extends TestCase
{
    public $userAgentService;
    public $faker;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->userAgentService = new UserAgentService(new UserAgentStatistic());
        $this->faker = Faker::create();
    }

    /**
     * A basic unit test example.
     *
     * @return void
     */
    public function testGetBrowserUnknown()
    {
        $browser = $this->userAgentService->getBrowser('Must return Unknown browser');
        $this->assertTrue($browser ==='Unknown');
    }

    public function testGetBrowser()
    {
        $browser = $this->userAgentService->getBrowser($this->faker->userAgent);
        $this->assertTrue($browser !== 'Unknown');
    }
}
